name: Terraform Azure Deployment

on:
  push:
    branches:
      - tf-rg-create

jobs:
  plan:
    name: Azure Infrasturcture Deployment
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

  #apply:
    #needs: plan
    #runs-on: self-hosted
    #environment:
      #name: approval-required
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply
        #run: terraform apply -auto-approve
