name: Terraform Azure Deployment

on:
  push:
    branches:
      - tf-rg-create

jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    #env:
      #ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      #ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        #uses: docker://alpine:latest
        uses: actions/checkout@v3
        #uses: owner/repo@ref
        #uses: actions/checkout

      - name: Setup Terraform
        #uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Azure Login 
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
